# Generated by Django 4.2.7 on 2025-05-30 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(choices=[('administrator', 'Administrator'), ('edytor', 'Edytor'), ('czytelnik', 'Czytelnik')], max_length=50, unique=True)),
                ('opis', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Rola',
                'verbose_name_plural': 'Role',
                'db_table': 'rola',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesja użytkownika',
                'verbose_name_plural': 'Sesje użytkowników',
                'db_table': 'user_session',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktywny', models.BooleanField(default=True)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('stanowisko', models.CharField(blank=True, max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('data_urodzenia', models.DateField(blank=True, null=True)),
                ('dwuetapowa_weryfikacja', models.BooleanField(default=False)),
                ('profil_publiczny', models.BooleanField(default=False)),
                ('rola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil użytkownika',
                'verbose_name_plural': 'Profile użytkowników',
                'db_table': 'user_profile',
            },
        ),
    ]
