# Generated by Django 5.2.2 on 2025-06-27 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_activitylog_options_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='wersja_dokumentu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='komentarze', to='documents.documentversion', verbose_name='Wersja dokumentu'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='tagi',
            field=models.ManyToManyField(blank=True, related_name='folders', to='documents.tag', verbose_name='Tagi'),
        ),
        migrations.DeleteModel(
            name='DocumentTag',
        ),
    ]
