# Generated by Django 4.2.7 on 2025-05-30 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50, unique=True)),
                ('kolor', models.CharField(default='#007bff', max_length=20)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('opis', models.TextField(blank=True)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('rodzic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podkatalogi', to='documents.folder')),
                ('wlasciciel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'folder',
                'permissions': (('browse_folder', 'Can browse folder'), ('share_folder', 'Can share folder'), ('manage_folder', 'Can manage folder permissions')),
                'unique_together': {('nazwa', 'rodzic', 'wlasciciel')},
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('typ_pliku', models.CharField(max_length=100)),
                ('rozmiar_pliku', models.PositiveIntegerField()),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('ostatnia_modyfikacja', models.DateTimeField(auto_now=True)),
                ('usunieto', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Szkic'), ('published', 'Opublikowany'), ('archived', 'Zarchiwizowany')], default='draft', max_length=20)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.folder')),
                ('tagi', models.ManyToManyField(blank=True, to='documents.tag')),
                ('wlasciciel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dokument',
                'ordering': ['-ostatnia_modyfikacja'],
                'permissions': (('browse_document', 'Can browse document'), ('download_document', 'Can download document'), ('share_document', 'Can share document'), ('comment_document', 'Can comment on document'), ('manage_document', 'Can manage document permissions')),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('dokument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentarze', to='documents.document')),
                ('rodzic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odpowiedzi', to='documents.comment')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'komentarz',
                'ordering': ['-data_utworzenia'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ_aktywnosci', models.CharField(choices=[('logowanie', 'Logowanie'), ('tworzenie', 'Tworzenie'), ('edycja', 'Edycja'), ('usuniecie', 'Usunięcie'), ('pobieranie', 'Pobieranie'), ('udostepnianie', 'Udostępnianie'), ('komentowanie', 'Komentowanie'), ('zmiana_uprawnien', 'Zmiana uprawnień')], max_length=50)),
                ('szczegoly', models.TextField(blank=True)),
                ('znacznik_czasu', models.DateTimeField(auto_now_add=True)),
                ('adres_ip', models.GenericIPAddressField()),
                ('dokument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.folder')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logi_aktywnosci', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'log_aktywnosci',
                'ordering': ['-znacznik_czasu'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_wersji', models.PositiveIntegerField()),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('zawartosc', models.FileField(upload_to='document_versions/')),
                ('komentarz', models.TextField(blank=True)),
                ('dokument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wersje', to='documents.document')),
                ('utworzony_przez', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wersja_dokumentu',
                'ordering': ['-numer_wersji'],
                'unique_together': {('dokument', 'numer_wersji')},
            },
        ),
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dokument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.tag')),
            ],
            options={
                'db_table': 'dokument_tag',
                'unique_together': {('dokument', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uprawnienie', models.CharField(choices=[('browse_document', 'Tylko przeglądanie'), ('download_document', 'Przeglądanie i pobieranie'), ('comment_document', 'Przeglądanie i komentowanie'), ('manage_document', 'Pełne uprawnienia do edycji')], max_length=50)),
                ('data_udostepnienia', models.DateTimeField(auto_now_add=True)),
                ('data_wygasniecia', models.DateTimeField(blank=True, null=True)),
                ('aktywne', models.BooleanField(default=True)),
                ('dokument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='documents.document')),
                ('udostepnione_dla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_documents', to=settings.AUTH_USER_MODEL)),
                ('udostepnione_przez', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_share',
                'unique_together': {('dokument', 'udostepnione_dla')},
            },
        ),
        migrations.CreateModel(
            name='DocumentMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klucz', models.CharField(max_length=100)),
                ('wartosc', models.TextField()),
                ('dokument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadane', to='documents.document')),
            ],
            options={
                'db_table': 'metadane',
                'unique_together': {('dokument', 'klucz')},
            },
        ),
    ]
