# Generated by Django 4.2.7 on 2025-05-30 22:10

import django.core.validators
from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Klucz')),
                ('value', models.TextField(verbose_name='Wartość')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('category', models.CharField(default='general', max_length=50, verbose_name='Kategoria')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ustawienie systemowe',
                'verbose_name_plural': 'Ustawienia systemowe',
                'db_table': 'system_settings',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.RemoveField(
            model_name='documentversion',
            name='zawartosc',
        ),
        migrations.AddField(
            model_name='document',
            name='hash_pliku',
            field=models.CharField(blank=True, help_text='SHA-256 hash for file integrity', max_length=64),
        ),
        migrations.AddField(
            model_name='document',
            name='opis',
            field=models.TextField(blank=True, help_text='Opcjonalny opis dokumentu'),
        ),
        migrations.AddField(
            model_name='document',
            name='plik',
            field=models.FileField(blank=True, help_text='Obsługiwane formaty: PDF, DOCX, DOC, XLSX, XLS, TXT, PNG, JPG, JPEG', null=True, upload_to=documents.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'xlsx', 'xls', 'txt', 'png', 'jpg', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='hash_pliku',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='plik',
            field=models.FileField(blank=True, null=True, upload_to='document_versions/'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='rozmiar_pliku',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='typ_aktywnosci',
            field=models.CharField(choices=[('logowanie', 'Logowanie'), ('tworzenie', 'Tworzenie'), ('edycja', 'Edycja'), ('usuniecie', 'Usunięcie'), ('pobieranie', 'Pobieranie'), ('udostepnianie', 'Udostępnianie'), ('komentowanie', 'Komentowanie'), ('zmiana_uprawnien', 'Zmiana uprawnień'), ('zmiana_hasla', 'Zmiana hasła')], max_length=50),
        ),
    ]
