# Generated by Django 4.2.7 on 2025-05-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_systemsettings_remove_documentversion_zawartosc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='tagi',
            field=models.ManyToManyField(blank=True, to='documents.tag', verbose_name='Tagi'),
        ),
    ]
