# Generated by Django 4.2.7 on 2025-05-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_folder_tagi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='typ_aktywnosci',
            field=models.CharField(choices=[('logowanie', 'Logowanie'), ('tworzenie', 'Tworzenie'), ('edycja', 'Edycja'), ('usuniecie', 'Usunięcie'), ('pobieranie', 'Pobieranie'), ('udostepnianie', 'Udostępnianie'), ('komentowanie', 'Komentowanie'), ('zmiana_uprawnien', 'Zmiana uprawnień'), ('zmiana_hasla', 'Zmiana hasła'), ('komentarz', 'Skomentowanie')], max_length=50),
        ),
    ]
