# Generated by Django 4.2.7 on 2025-05-31 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0004_alter_activitylog_typ_aktywnosci'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['data_utworzenia'], 'verbose_name': 'Komentarz', 'verbose_name_plural': 'Komentarze'},
        ),
        migrations.AddField(
            model_name='comment',
            name='aktywny',
            field=models.BooleanField(default=True, verbose_name='Aktywny'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='data_utworzenia',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dokument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentarze', to='documents.document', verbose_name='Dokument'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rodzic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odpowiedzi', to='documents.comment', verbose_name='Komentarz nadrzędny'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='tresc',
            field=models.TextField(verbose_name='Treść komentarza'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='uzytkownik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
    ]
