# Generated by Django 4.2.7 on 2025-05-31 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0005_alter_comment_options_comment_aktywny_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-znacznik_czasu'], 'verbose_name': 'Log aktywności', 'verbose_name_plural': 'Logi aktywności'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-ostatnia_modyfikacja'], 'permissions': (('browse_document', 'Can browse document'), ('share_document', 'Can share document with others'), ('download_document', 'Can download document file'), ('comment_document', 'Can comment on document')), 'verbose_name': 'Dokument', 'verbose_name_plural': 'Dokumenty'},
        ),
        migrations.AlterModelOptions(
            name='documentmetadata',
            options={'verbose_name': 'Metadana dokumentu', 'verbose_name_plural': 'Metadane dokumentów'},
        ),
        migrations.AlterModelOptions(
            name='documentshare',
            options={'verbose_name': 'Udostępnienie dokumentu', 'verbose_name_plural': 'Udostępnienia dokumentów'},
        ),
        migrations.AlterModelOptions(
            name='documenttag',
            options={'verbose_name': 'Tag dokumentu', 'verbose_name_plural': 'Tagi dokumentów'},
        ),
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['nazwa'], 'permissions': (('browse_folder', 'Can browse folder and its contents'), ('add_document_to_folder', 'Can add documents to folder'), ('add_subfolder_to_folder', 'Can add subfolders to folder')), 'verbose_name': 'Folder', 'verbose_name_plural': 'Foldery'},
        ),
        migrations.AlterModelOptions(
            name='systemsettings',
            options={'ordering': ['kategoria', 'klucz'], 'verbose_name': 'Ustawienie systemowe', 'verbose_name_plural': 'Ustawienia systemowe'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['nazwa'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tagi'},
        ),
        migrations.RenameField(
            model_name='systemsettings',
            old_name='updated_at',
            new_name='data_modyfikacji',
        ),
        migrations.RenameField(
            model_name='systemsettings',
            old_name='created_at',
            new_name='data_utworzenia',
        ),
        migrations.RenameField(
            model_name='systemsettings',
            old_name='category',
            new_name='kategoria',
        ),
        migrations.RenameField(
            model_name='systemsettings',
            old_name='key',
            new_name='klucz',
        ),
        migrations.RenameField(
            model_name='systemsettings',
            old_name='description',
            new_name='opis',
        ),
        migrations.RenameField(
            model_name='systemsettings',
            old_name='value',
            new_name='wartosc',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='adres_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='dokument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.folder'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='typ_aktywnosci',
            field=models.CharField(choices=[('logowanie', 'Logowanie'), ('tworzenie', 'Tworzenie'), ('edycja', 'Edycja'), ('usuniecie', 'Usunięcie'), ('pobieranie', 'Pobieranie'), ('udostepnianie', 'Udostępnianie'), ('komentowanie', 'Komentowanie'), ('zmiana_uprawnien', 'Zmiana uprawnień'), ('zmiana_hasla', 'Zmiana hasła')], max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.folder'),
        ),
        migrations.AlterField(
            model_name='document',
            name='rozmiar_pliku',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='tagi',
            field=models.ManyToManyField(blank=True, related_name='documents', to='documents.tag'),
        ),
        migrations.AlterField(
            model_name='document',
            name='typ_pliku',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='wlasciciel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentshare',
            name='dokument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_shares', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='documentshare',
            name='udostepnione_dla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentshare',
            name='udostepnione_przez',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='made_shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentshare',
            name='uprawnienie',
            field=models.CharField(choices=[('documents.browse_document', 'Tylko przeglądanie'), ('documents.download_document', 'Przeglądanie i pobieranie'), ('documents.comment_document', 'Przeglądanie i komentowanie'), ('documents.change_document', 'Pełne uprawnienia do edycji')], max_length=100),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='plik',
            field=models.FileField(blank=True, null=True, upload_to='document_versions/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='rozmiar_pliku',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='wlasciciel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
