# Generated by Django 4.2 on 2025-06-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_comment_wersja_dokumentu_alter_folder_tagi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='oryginalna_nazwa_pliku',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
